create table OfficeData
(
    OfficeKey                   varchar(255) not null
        primary key,
    FranchiseAffiliation        varchar(50)  null,
    IDXOfficeParticipationYN    tinyint(1)   null,
    MainOfficeKey               varchar(255) null,
    MainOfficeMlsId             varchar(25)  null,
    ModificationTimestamp       datetime     null,
    OfficeAOR                   varchar(50)  null,
    OfficeAORMlsId              varchar(25)  null,
    OfficeAORkey                varchar(255) null,
    OfficeAddress1              varchar(50)  null,
    OfficeAddress2              varchar(50)  null,
    OfficeAssociationComments   varchar(500) null,
    OfficeBranchType            varchar(50)  null,
    OfficeBrokerKey             varchar(255) null,
    OfficeBrokerMlsId           varchar(25)  null,
    OfficeCity                  varchar(50)  null,
    OfficeCorporateLicense      varchar(50)  null,
    OfficeCountyOrParish        varchar(50)  null,
    OfficeEmail                 varchar(80)  null,
    OfficeFax                   varchar(16)  null,
    OfficeManagerKey            varchar(255) null,
    OfficeManagerMlsId          varchar(25)  null,
    OfficeMlsId                 varchar(25)  null,
    OfficeName                  varchar(255) null,
    OfficeNationalAssociationId varchar(25)  null,
    OfficePhone                 varchar(16)  null,
    OfficePhoneExt              varchar(10)  null,
    OfficePostalCode            varchar(10)  null,
    OfficePostalCodePlus4       varchar(4)   null,
    OfficeStateOrProvince       varchar(2)   null,
    OfficeStatus                varchar(25)  null,
    OfficeType                  varchar(50)  null,
    OriginalEntryTimestamp      datetime     null,
    OriginatingSystemID         varchar(25)  null,
    OriginatingSystemName       varchar(255) null,
    OriginatingSystemOfficeKey  varchar(255) null,
    SocialMediaType             varchar(25)  null,
    SourceSystemID              varchar(25)  null,
    SourceSystemName            varchar(255) null,
    SourceSystemOfficeKey       varchar(255) null,
    SyndicateAgentOption        varchar(50)  null,
    SyndicateTo                 json         null,
    MainOffice                  blob         null,
    OfficeBroker                blob         null,
    OfficeManager               blob         null,
    OriginatingSystem           blob         null,
    SourceSystem                blob         null,
    HistoryTransactional        blob         null,
    Media                       blob         null,
    OfficeSocialMedia           blob         null
);

