create table ParagonRawOffice
(
    Office_Abbreviation       varchar(15)  not null
        primary key,
    `Active...`               tinyint(1)   null,
    Board_ID                  varchar(10)  null,
    Date_Added                datetime     null,
    MLS_Member                blob         null,
    Office_Url                varchar(80)  null,
    Office_Zip                varchar(20)  null,
    IDX_Include               tinyint(1)   null,
    Office_City               varchar(50)  null,
    Office_Name               varchar(100) null,
    Office_Type               varchar(3)   null,
    Update_Date               datetime     null,
    Board_Member              varchar(1)   null,
    Office_Email              varchar(50)  null,
    Office_State              varchar(2)   null,
    Main_Office_ID            int          null,
    Office_Contact            varchar(20)  null,
    Point2_Enabled            varchar(1)   null,
    Office_Address2           varchar(50)  null,
    Office_Mail_Zip           varchar(20)  null,
    Office_Mail_City          varchar(50)  null,
    Office_Identifier         int          null,
    Office_Mail_State         varchar(2)   null,
    Designated_Broker_ID      int          null,
    Office_Mail_Address2      varchar(50)  null,
    Office_Phone1_Number      varchar(30)  null,
    Office_Phone2_Number      varchar(30)  null,
    Office_Phone3_Number      varchar(30)  null,
    Office_Computer_Access    varchar(1)   null,
    Office_Mail_Street_Name   varchar(50)  null,
    Office_Phone1_CountryId   varchar(10)  null,
    Office_Phone1_Extension   varchar(5)   null,
    Office_Phone2_CountryId   varchar(10)  null,
    Office_Phone2_Extension   varchar(5)   null,
    Office_Phone3_CountryId   varchar(10)  null,
    Office_Phone3_Extension   varchar(5)   null,
    Homesnap_Showings_Opt_In  varchar(10)  null,
    Offce_Address_Street_Name varchar(50)  null,
    Office_Phone1_Description varchar(10)  null,
    Office_Phone2_Description varchar(10)  null,
    Office_Phone3_Description varchar(10)  null,
    National_RDS_Number       varchar(15)  null
)
    engine = MyISAM
    KEY_BLOCK_SIZE = 8
    row_format = COMPRESSED;

